name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm test
      env:
        ADYEN_API_KEY: ${{ secrets.ADYEN_API_KEY }}
        ADYEN_MERCHANT_ACCOUNT: ${{ secrets.ADYEN_MERCHANT_ACCOUNT }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    - run: npm run build
